export type RoleName = 'SUPER_ADMIN' | 'HR_MANAGER' | 'OPERATIONAL_MANAGER' | 'EMPLOYEE';

export type ScopeLevel = 'SELF' | 'TEAM' | 'DEPARTMENT' | 'ORGANIZATION';

export interface PermissionDefinition {
  key: string;
  module: string;
  action: string;
  description: string;
}

export type RolePermissionMatrix = Record<string, Record<string, ScopeLevel>>;

/**
 * Normalizes role string to canonical 4-role system: SUPER_ADMIN, HR_MANAGER, OPERATIONAL_MANAGER, EMPLOYEE
 */
export function normalizeRole(role?: string | null): RoleName {
  if (!role) return 'EMPLOYEE';
  const upper = role.trim().toUpperCase();
  if (upper === 'SUPER_ADMIN' || upper === 'ADMIN' || upper === 'ADMINISTRATOR') return 'SUPER_ADMIN';
  if (upper === 'HR_MANAGER' || upper === 'HR_ADMIN' || upper === 'HR_EXECUTIVE') return 'HR_MANAGER';
  if (upper === 'OPERATIONAL_MANAGER' || upper === 'MANAGER' || upper === 'FINANCE' || upper === 'TEAM_LEAD') return 'OPERATIONAL_MANAGER';
  return 'EMPLOYEE';
}

/**
 * Centralized Role -> Permission -> Scope Matrix
 */
export const ROLE_PERMISSIONS: RolePermissionMatrix = {
  SUPER_ADMIN: {
    // Implicit full access to all permissions at ORGANIZATION level
    '*': 'ORGANIZATION'
  },
  HR_MANAGER: {
    EMPLOYEE_VIEW_WORKFORCE: 'ORGANIZATION',
    EMPLOYEE_CREATE: 'ORGANIZATION',
    EMPLOYEE_UPDATE: 'ORGANIZATION',
    EMPLOYEE_VIEW_SELF: 'SELF',

    ATTENDANCE_SELF_PUNCH: 'SELF',
    ATTENDANCE_SELF_VIEW: 'SELF',
    ATTENDANCE_WORKFORCE_VIEW: 'ORGANIZATION',
    ATTENDANCE_GPS_VIEW: 'ORGANIZATION',
    ATTENDANCE_REGULARIZE: 'ORGANIZATION',

    LEAVE_SELF_APPLY: 'SELF',
    LEAVE_SELF_VIEW: 'SELF',
    LEAVE_WORKFORCE_VIEW: 'ORGANIZATION',
    LEAVE_APPROVE: 'ORGANIZATION',
    LEAVE_POLICY_MANAGE: 'ORGANIZATION',
    LEAVE_BALANCE_MANAGE: 'ORGANIZATION',

    EXPENSE_SELF_CREATE: 'SELF',
    EXPENSE_SELF_VIEW: 'SELF',
    EXPENSE_WORKFORCE_VIEW: 'ORGANIZATION',
    EXPENSE_APPROVE: 'ORGANIZATION',
    EXPENSE_REJECT: 'ORGANIZATION',
    TRIP_EXPENSE_SELF_CREATE: 'SELF',
    TRIP_EXPENSE_WORKFORCE_VIEW: 'ORGANIZATION',
    TRIP_EXPENSE_APPROVE: 'ORGANIZATION',
    TRIP_EXPENSE_REJECT: 'ORGANIZATION',

    ASSET_SELF_VIEW: 'SELF',
    ASSET_WORKFORCE_VIEW: 'ORGANIZATION',
    ASSET_CREATE: 'ORGANIZATION',
    ASSET_UPDATE: 'ORGANIZATION',
    ASSET_ASSIGN: 'ORGANIZATION',
    ASSET_RETURN: 'ORGANIZATION',
    ASSET_CATEGORY_MANAGE: 'ORGANIZATION',
    ASSET_REQUEST_CREATE: 'SELF',
    ASSET_REQUEST_APPROVE: 'ORGANIZATION',
    ASSET_REQUEST_FULFILL: 'ORGANIZATION',

    TASK_SELF_CREATE: 'SELF',
    TASK_SELF_VIEW: 'SELF',
    TASK_WORKFORCE_VIEW: 'ORGANIZATION',
    TASK_ASSIGN: 'ORGANIZATION',
    TASK_UPDATE: 'ORGANIZATION',

    CALENDAR_SELF_VIEW: 'SELF',
    CALENDAR_WORKFORCE_VIEW: 'ORGANIZATION',
    REPORTS_WORKFORCE_VIEW: 'ORGANIZATION',
    NOTIFICATIONS_SELF_VIEW: 'SELF',
    NOTIFICATIONS_MANAGE: 'ORGANIZATION',
    USER_PASSWORD_RESET: 'ORGANIZATION'
  },
  OPERATIONAL_MANAGER: {
    EMPLOYEE_VIEW_WORKFORCE: 'ORGANIZATION',
    EMPLOYEE_VIEW_SELF: 'SELF',
    ATTENDANCE_SELF_PUNCH: 'SELF',
    ATTENDANCE_SELF_VIEW: 'SELF',
    ATTENDANCE_WORKFORCE_VIEW: 'ORGANIZATION',
    ATTENDANCE_GPS_VIEW: 'ORGANIZATION',
    LEAVE_SELF_APPLY: 'SELF',
    LEAVE_SELF_VIEW: 'SELF',
    LEAVE_WORKFORCE_VIEW: 'ORGANIZATION',
    LEAVE_APPROVE: 'ORGANIZATION',
    EXPENSE_SELF_CREATE: 'SELF',
    EXPENSE_SELF_VIEW: 'SELF',
    EXPENSE_WORKFORCE_VIEW: 'ORGANIZATION',
    EXPENSE_APPROVE: 'ORGANIZATION',
    EXPENSE_REJECT: 'ORGANIZATION',
    TRIP_EXPENSE_SELF_CREATE: 'SELF',
    TRIP_EXPENSE_WORKFORCE_VIEW: 'ORGANIZATION',
    TRIP_EXPENSE_APPROVE: 'ORGANIZATION',
    TRIP_EXPENSE_REJECT: 'ORGANIZATION',
    ASSET_SELF_VIEW: 'SELF',
    ASSET_WORKFORCE_VIEW: 'ORGANIZATION',
    ASSET_REQUEST_CREATE: 'SELF',
    TASK_SELF_CREATE: 'SELF',
    TASK_SELF_VIEW: 'SELF',
    TASK_WORKFORCE_VIEW: 'ORGANIZATION',
    TASK_ASSIGN: 'ORGANIZATION',
    TASK_UPDATE: 'ORGANIZATION',
    CALENDAR_SELF_VIEW: 'SELF',
    CALENDAR_WORKFORCE_VIEW: 'ORGANIZATION',
    REPORTS_WORKFORCE_VIEW: 'ORGANIZATION',
    NOTIFICATIONS_SELF_VIEW: 'SELF'
  },
  EMPLOYEE: {
    EMPLOYEE_VIEW_SELF: 'SELF',
    ATTENDANCE_SELF_PUNCH: 'SELF',
    ATTENDANCE_SELF_VIEW: 'SELF',
    LEAVE_SELF_APPLY: 'SELF',
    LEAVE_SELF_VIEW: 'SELF',
    EXPENSE_SELF_CREATE: 'SELF',
    EXPENSE_SELF_VIEW: 'SELF',
    TRIP_EXPENSE_SELF_CREATE: 'SELF',
    ASSET_SELF_VIEW: 'SELF',
    ASSET_REQUEST_CREATE: 'SELF',
    TASK_SELF_CREATE: 'SELF',
    TASK_SELF_VIEW: 'SELF',
    CALENDAR_SELF_VIEW: 'SELF',
    NOTIFICATIONS_SELF_VIEW: 'SELF'
  }
};

// Aliases for matrix lookups
ROLE_PERMISSIONS.ADMIN = ROLE_PERMISSIONS.SUPER_ADMIN;
ROLE_PERMISSIONS.MANAGER = ROLE_PERMISSIONS.HR_MANAGER;

/**
 * Checks if a given role possesses a specific permission and required minimum scope.
 */
export function hasPermission(
  role: string | undefined | null,
  permissionKey: string,
  requiredScope?: ScopeLevel
): boolean {
  const canonicalRole = normalizeRole(role);
  if (canonicalRole === 'SUPER_ADMIN') return true;

  const roleMap = ROLE_PERMISSIONS[canonicalRole];
  if (!roleMap) return false;

  const grantedScope = roleMap[permissionKey];
  if (!grantedScope) return false;

  if (!requiredScope) return true;

  // Scope hierarchy comparison: ORGANIZATION > DEPARTMENT > TEAM > SELF
  const scopeOrder: Record<ScopeLevel, number> = {
    SELF: 1,
    TEAM: 2,
    DEPARTMENT: 3,
    ORGANIZATION: 4
  };

  return scopeOrder[grantedScope] >= scopeOrder[requiredScope];
}
