export type ScopeLevel = 'SELF' | 'TEAM' | 'DEPARTMENT' | 'ORGANIZATION';

export type RolePermissionMatrix = Record<string, Record<string, ScopeLevel>>;

/**
 * Normalizes role string to canonical role name
 */
export function normalizeRole(role?: string | null): string {
  if (!role) return 'EMPLOYEE';
  const upper = role.trim().toUpperCase();
  if (upper === 'ADMINISTRATOR') return 'ADMIN';
  return upper;
}

/**
 * Centralized Role -> Permission -> Scope Matrix (Frontend Mirror)
 */
export const ROLE_PERMISSIONS: RolePermissionMatrix = {
  SUPER_ADMIN: {
    '*': 'ORGANIZATION'
  },
  ADMIN: {
    EMPLOYEE_VIEW_WORKFORCE: 'ORGANIZATION',
    EMPLOYEE_CREATE: 'ORGANIZATION',
    EMPLOYEE_UPDATE: 'ORGANIZATION',
    EMPLOYEE_VIEW_SELF: 'SELF',

    ATTENDANCE_SELF_PUNCH: 'SELF',
    ATTENDANCE_SELF_VIEW: 'SELF',
    ATTENDANCE_WORKFORCE_VIEW: 'ORGANIZATION',
    ATTENDANCE_GPS_VIEW: 'ORGANIZATION',
    ATTENDANCE_REGULARIZE: 'ORGANIZATION',

    LEAVE_SELF_APPLY: 'SELF',
    LEAVE_SELF_VIEW: 'SELF',
    LEAVE_WORKFORCE_VIEW: 'ORGANIZATION',
    LEAVE_APPROVE: 'ORGANIZATION',
    LEAVE_POLICY_MANAGE: 'ORGANIZATION',
    LEAVE_BALANCE_MANAGE: 'ORGANIZATION',

    EXPENSE_SELF_CREATE: 'SELF',
    EXPENSE_SELF_VIEW: 'SELF',
    EXPENSE_WORKFORCE_VIEW: 'ORGANIZATION',
    EXPENSE_APPROVE: 'ORGANIZATION',
    EXPENSE_REJECT: 'ORGANIZATION',
    TRIP_EXPENSE_SELF_CREATE: 'SELF',
    TRIP_EXPENSE_WORKFORCE_VIEW: 'ORGANIZATION',
    TRIP_EXPENSE_APPROVE: 'ORGANIZATION',
    TRIP_EXPENSE_REJECT: 'ORGANIZATION',

    ASSET_SELF_VIEW: 'SELF',
    ASSET_WORKFORCE_VIEW: 'ORGANIZATION',
    ASSET_CREATE: 'ORGANIZATION',
    ASSET_UPDATE: 'ORGANIZATION',
    ASSET_ASSIGN: 'ORGANIZATION',
    ASSET_RETURN: 'ORGANIZATION',
    ASSET_CATEGORY_MANAGE: 'ORGANIZATION',
    ASSET_REQUEST_CREATE: 'SELF',
    ASSET_REQUEST_APPROVE: 'ORGANIZATION',
    ASSET_REQUEST_FULFILL: 'ORGANIZATION',

    TASK_SELF_CREATE: 'SELF',
    TASK_SELF_VIEW: 'SELF',
    TASK_WORKFORCE_VIEW: 'ORGANIZATION',
    TASK_ASSIGN: 'ORGANIZATION',
    TASK_UPDATE: 'ORGANIZATION',

    CALENDAR_SELF_VIEW: 'SELF',
    CALENDAR_WORKFORCE_VIEW: 'ORGANIZATION',
    REPORTS_WORKFORCE_VIEW: 'ORGANIZATION',
    NOTIFICATIONS_SELF_VIEW: 'SELF',
    NOTIFICATIONS_MANAGE: 'ORGANIZATION',
    AUDIT_LOG_VIEW: 'ORGANIZATION',

    USER_VIEW: 'ORGANIZATION',
    USER_CREATE: 'ORGANIZATION',
    USER_UPDATE: 'ORGANIZATION',
    USER_ROLE_ASSIGN: 'ORGANIZATION',
    USER_PASSWORD_RESET: 'ORGANIZATION'
  },
  HR_MANAGER: {
    EMPLOYEE_VIEW_WORKFORCE: 'ORGANIZATION',
    EMPLOYEE_CREATE: 'ORGANIZATION',
    EMPLOYEE_UPDATE: 'ORGANIZATION',
    EMPLOYEE_VIEW_SELF: 'SELF',

    ATTENDANCE_SELF_PUNCH: 'SELF',
    ATTENDANCE_SELF_VIEW: 'SELF',
    ATTENDANCE_WORKFORCE_VIEW: 'ORGANIZATION',
    ATTENDANCE_GPS_VIEW: 'ORGANIZATION',
    ATTENDANCE_REGULARIZE: 'ORGANIZATION',

    LEAVE_SELF_APPLY: 'SELF',
    LEAVE_SELF_VIEW: 'SELF',
    LEAVE_WORKFORCE_VIEW: 'ORGANIZATION',
    LEAVE_APPROVE: 'ORGANIZATION',
    LEAVE_POLICY_MANAGE: 'ORGANIZATION',
    LEAVE_BALANCE_MANAGE: 'ORGANIZATION',

    EXPENSE_SELF_CREATE: 'SELF',
    EXPENSE_SELF_VIEW: 'SELF',
    EXPENSE_WORKFORCE_VIEW: 'ORGANIZATION',
    EXPENSE_APPROVE: 'ORGANIZATION',
    EXPENSE_REJECT: 'ORGANIZATION',
    TRIP_EXPENSE_SELF_CREATE: 'SELF',
    TRIP_EXPENSE_WORKFORCE_VIEW: 'ORGANIZATION',
    TRIP_EXPENSE_APPROVE: 'ORGANIZATION',
    TRIP_EXPENSE_REJECT: 'ORGANIZATION',

    ASSET_SELF_VIEW: 'SELF',
    ASSET_WORKFORCE_VIEW: 'ORGANIZATION',
    ASSET_CREATE: 'ORGANIZATION',
    ASSET_UPDATE: 'ORGANIZATION',
    ASSET_ASSIGN: 'ORGANIZATION',
    ASSET_RETURN: 'ORGANIZATION',
    ASSET_CATEGORY_MANAGE: 'ORGANIZATION',
    ASSET_REQUEST_CREATE: 'SELF',
    ASSET_REQUEST_APPROVE: 'ORGANIZATION',
    ASSET_REQUEST_FULFILL: 'ORGANIZATION',

    TASK_SELF_CREATE: 'SELF',
    TASK_SELF_VIEW: 'SELF',
    TASK_WORKFORCE_VIEW: 'ORGANIZATION',
    TASK_ASSIGN: 'ORGANIZATION',
    TASK_UPDATE: 'ORGANIZATION',

    CALENDAR_SELF_VIEW: 'SELF',
    CALENDAR_WORKFORCE_VIEW: 'ORGANIZATION',
    REPORTS_WORKFORCE_VIEW: 'ORGANIZATION',
    NOTIFICATIONS_SELF_VIEW: 'SELF',
    NOTIFICATIONS_MANAGE: 'ORGANIZATION',
    USER_PASSWORD_RESET: 'ORGANIZATION'
  },
  OPERATIONAL_MANAGER: {
    EMPLOYEE_VIEW_WORKFORCE: 'TEAM',
    EMPLOYEE_CREATE: 'TEAM',
    EMPLOYEE_UPDATE: 'TEAM',
    EMPLOYEE_VIEW_SELF: 'SELF',

    ATTENDANCE_SELF_PUNCH: 'SELF',
    ATTENDANCE_SELF_VIEW: 'SELF',
    ATTENDANCE_WORKFORCE_VIEW: 'TEAM',
    ATTENDANCE_GPS_VIEW: 'TEAM',

    LEAVE_SELF_APPLY: 'SELF',
    LEAVE_SELF_VIEW: 'SELF',
    LEAVE_WORKFORCE_VIEW: 'TEAM',
    LEAVE_APPROVE: 'TEAM',

    EXPENSE_SELF_CREATE: 'SELF',
    EXPENSE_SELF_VIEW: 'SELF',
    EXPENSE_WORKFORCE_VIEW: 'TEAM',
    EXPENSE_APPROVE: 'TEAM',
    EXPENSE_REJECT: 'TEAM',
    TRIP_EXPENSE_SELF_CREATE: 'SELF',
    TRIP_EXPENSE_WORKFORCE_VIEW: 'TEAM',
    TRIP_EXPENSE_APPROVE: 'TEAM',
    TRIP_EXPENSE_REJECT: 'TEAM',

    ASSET_SELF_VIEW: 'SELF',
    ASSET_WORKFORCE_VIEW: 'TEAM',
    ASSET_ASSIGN: 'TEAM',
    ASSET_RETURN: 'TEAM',
    ASSET_REQUEST_CREATE: 'SELF',
    ASSET_REQUEST_APPROVE: 'TEAM',

    TASK_SELF_CREATE: 'SELF',
    TASK_SELF_VIEW: 'SELF',
    TASK_WORKFORCE_VIEW: 'TEAM',
    TASK_ASSIGN: 'TEAM',
    TASK_UPDATE: 'TEAM',

    CALENDAR_SELF_VIEW: 'SELF',
    CALENDAR_WORKFORCE_VIEW: 'TEAM',
    REPORTS_WORKFORCE_VIEW: 'TEAM',
    NOTIFICATIONS_SELF_VIEW: 'SELF'
  },
  EMPLOYEE: {
    EMPLOYEE_VIEW_SELF: 'SELF',
    ATTENDANCE_SELF_PUNCH: 'SELF',
    ATTENDANCE_SELF_VIEW: 'SELF',
    LEAVE_SELF_APPLY: 'SELF',
    LEAVE_SELF_VIEW: 'SELF',
    EXPENSE_SELF_CREATE: 'SELF',
    EXPENSE_SELF_VIEW: 'SELF',
    TRIP_EXPENSE_SELF_CREATE: 'SELF',
    ASSET_SELF_VIEW: 'SELF',
    ASSET_REQUEST_CREATE: 'SELF',
    TASK_SELF_CREATE: 'SELF',
    TASK_SELF_VIEW: 'SELF',
    CALENDAR_SELF_VIEW: 'SELF',
    NOTIFICATIONS_SELF_VIEW: 'SELF'
  }
};

/**
 * Checks if a given role possesses a specific permission key and required minimum scope level.
 */
export function hasPermission(
  role: string | undefined | null,
  permissionKey: string,
  requiredScope?: ScopeLevel
): boolean {
  const canonicalRole = normalizeRole(role);
  if (canonicalRole === 'SUPER_ADMIN') return true;

  const roleMap = ROLE_PERMISSIONS[canonicalRole];
  if (!roleMap) return false;

  const grantedScope = roleMap[permissionKey];
  if (!grantedScope) return false;

  if (!requiredScope) return true;

  const scopeOrder: Record<ScopeLevel, number> = {
    SELF: 1,
    TEAM: 2,
    DEPARTMENT: 3,
    ORGANIZATION: 4
  };

  return scopeOrder[grantedScope] >= scopeOrder[requiredScope];
}

/**
 * Returns list of roles that an actor role is authorized to assign to another account
 */
export function getAllowedAssignableRoles(actorRole?: string | null): string[] {
  const canonicalRole = normalizeRole(actorRole);
  switch (canonicalRole) {
    case 'SUPER_ADMIN':
      return ['SUPER_ADMIN', 'ADMIN', 'HR_MANAGER', 'OPERATIONAL_MANAGER', 'EMPLOYEE'];
    case 'ADMIN':
      return ['HR_MANAGER', 'OPERATIONAL_MANAGER', 'EMPLOYEE'];
    case 'HR_MANAGER':
      return ['OPERATIONAL_MANAGER', 'EMPLOYEE'];
    case 'OPERATIONAL_MANAGER':
    case 'EMPLOYEE':
    default:
      return [];
  }
}
